### ISSUE TITLE
Update color maps to include additions in May 2018

### ISSUE THREAD

**Issue by coatless** [coatless/cetcolor#4]
c.f. https://peterkovesi.com/projects/colourmaps/

Note: **Update May 2018: New colour maps L16-L19, D1A and D13**

WIP in #6

**Comment by coatless** [comment]
@peterkovesi Do you have an RSS feed or a repository that contains either the raw CSVs or a changelog/NEWS file? Seems like I've missed a few updates to the CET Colour maps. I'd like to figure out a way to stay aware of any changes.

**Comment by peterkovesi** [comment]
@coatless a zip file of raw CSV files can be downloaded from https://peterkovesi.com/projects/colourmaps/index.html
In addition to L16-L19 and D1A and D13 I have also constructed some colour maps that (supposedly) lie within the colour space of those who are colour blind.  Probably the only ones worth including are CBL1, CBL2, CBD1, CBC1 and CBC2. I have no idea how useful these might be...

I might look at RSS but I am not sure there is enough changing to justify it

**Comment by coatless** [comment]
@peterkovesi thank you for the information! 

Don't worry about the RSS feed. I'll subscribe to the Julia package that you maintain at: [PerceptualColourMaps.jl](https://github.com/peterkovesi/PerceptualColourMaps.jl). This should allow me to see if you are making changes. 

Please do consider storing the output from the scripts into a repo to see if any RGB values change. One CSV had slightly fluctuation in numbers _close_ to zero, c.f. https://github.com/coatless/cetcolor/pull/6/commits/b416aef7a39c13ec3039c39f92761f4859675b86#diff-b743d66761ddf4aa755d395ce4382220
